name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:
  # schedule:
  #   - cron:  '0 */4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - run: npm ci

      # - run: node .
      #   env:
      #     STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
      #     STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
      #     STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}

      # - uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: Updated activity list

      - run: npm run website-build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/dist
